# Generated by Django 4.2.11 on 2025-12-30 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_id'),
        ('users', '0004_user_is_email_verified'),
    ]

    operations = [
    ]
