# Generated by Django 5.2.5 on 2025-09-17 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("portofolio", "0006_article_content_article_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientProfile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, null=True)),
                ("phone", models.CharField(max_length=11, null=True)),
                ("gender", models.CharField(max_length=10, null=True)),
                ("address", models.CharField(max_length=30, null=True)),
                ("date_of_birth", models.DateField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(null=True)),
                ("diagnosis", models.CharField(max_length=255, null=True)),
                ("treatment", models.CharField(max_length=255, null=True)),
                ("notes", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "doctor_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portofolio.dentistprofile",
                    ),
                ),
                (
                    "patient_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patientprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medicine_name", models.CharField(max_length=255, null=True)),
                ("dosage", models.CharField(max_length=255, null=True)),
                ("duration", models.IntegerField(null=True)),
                ("instructions", models.TextField(null=True)),
                ("prescribed_date", models.DateField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "medical_record",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.medicalrecord",
                    ),
                ),
            ],
        ),
    ]
