# Generated by Django 5.2.5 on 2025-12-06 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0001_initial"),
        ("portofolio", "0009_alter_dentistprofile_profile_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientDoctorRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                        ],
                        default="active",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("assigned_date", models.DateField(auto_now_add=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "doctor_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_patients",
                        to="portofolio.dentistprofile",
                    ),
                ),
                (
                    "patient_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_doctors",
                        to="patient.patientprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("patient_id", "doctor_id")},
            },
        ),
    ]
