# Generated by Django 5.2.5 on 2025-12-08 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [

        ("patient", "0002_patientdoctorrelationship"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        migrations.AddField(
            model_name="medicalrecord",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="AITreatmentSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "input_data",
                    models.TextField(
                        help_text="Symptoms or input data provided by patient"
                    ),
                ),
                (
                    "ai_diagnosis",
                    models.TextField(help_text="Diagnosis predicted by AI"),
                ),
                (
                    "ai_treatment_plan",
                    models.TextField(help_text="Treatment plan suggested by AI"),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        blank=True, help_text="AI confidence score (0-100)", null=True
                    ),
                ),
                (
                    "doctor_verdict",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("modified", "Modified & Approved"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "doctor_notes",
                    models.TextField(
                        blank=True,
                        help_text="Doctor's feedback on the AI suggestion",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_suggestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),


            ],
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="ai_suggestion",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="medical_record",
                to="patient.aitreatmentsuggestion",
            ),
        ),
        migrations.CreateModel(
            name="MedicalAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_url",
                    models.URLField(
                        help_text="Direct link to the file (e.g., S3, Cloudinary, or external host)",
                        max_length=500,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="patient.medicalrecord",
                    ),
                ),
            ],
        ),
    ]
