# Generated by Django 5.2.5 on 2026-02-15 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0003_medicalrecord_appointment_medicalrecord_clinic_and_more"),
        ("portofolio", "0009_alter_dentistprofile_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="aitreatmentsuggestion",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="portofolio.dentistprofile",
            ),
        ),
    ]
