# Generated by Django 4.2.11 on 2026-02-20 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0004_aitreatmentsuggestion_reviewed_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.TextField(null=True)),
                ('confidence_score', models.FloatField(null=True)),
                ('probabilities', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medical_record',
        ),
        migrations.RenameField(
            model_name='medicalattachment',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='medicalattachment',
            name='record',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='ai_suggestion',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='date',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='treatment',
        ),
        migrations.AddField(
            model_name='medicalattachment',
            name='medical_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='patient.medicalrecord'),
        ),
        migrations.AlterField(
            model_name='medicalattachment',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medicalattachment',
            name='file_url',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='AITreatmentSuggestion',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='ai_result',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_record', to='patient.airesult'),
        ),
    ]
