# Generated by Django 4.2.11 on 2026-02-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_add_medicalattachment_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='airesult',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airesult',
            name='suggestion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
