# Generated by Django 5.2.5 on 2025-09-01 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0001_initial'),
    ]

    operations = [
    ]
