# Generated by Django 5.2.5 on 2025-09-01 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0002_auto_20250901_0712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='experiance',
            name='Organization',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='experiance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='experiance',
            name='dentist_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portofolio.dentistprofile'),
        ),
        migrations.AddField(
            model_name='experiance',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='experiance',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiance',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='experiance',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='experiance',
            table='portofolio_experiance',
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('Organization', models.CharField(max_length=255, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('dentist_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portofolio.dentistprofile')),
            ],
        ),
    ]
