# Generated by Django 5.2.4 on 2025-09-01 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0003_article_socialmedia_experiance_organization_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Experiance',
        ),
    ]
