# Generated by Django 5.2.4 on 2025-09-01 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0004_delete_experiance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='created_at',
        ),
    ]
