# Generated by Django 5.2.5 on 2025-09-17 13:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portofolio", "0005_remove_experience_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="content",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="article",
            name="dentist_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="portofolio.dentistprofile",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="awards",
            name="date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="awards",
            name="dentist_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="portofolio.dentistprofile",
            ),
        ),
        migrations.AddField(
            model_name="awards",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="awards",
            name="image",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="awards",
            name="title",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="certification",
            name="credential_url",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="certification",
            name="dentist_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="portofolio.dentistprofile",
            ),
        ),
        migrations.AddField(
            model_name="certification",
            name="expiry_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="certification",
            name="image",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="certification",
            name="issue_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="certification",
            name="issued_by",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="certification",
            name="name",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="dentistprofile",
            name="bio",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="dentistprofile",
            name="clinic_address",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="dentistprofile",
            name="clinic_name",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="dentistprofile",
            name="phone_number",
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="dentistprofile",
            name="profile_image",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="dentistprofile",
            name="specialty",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="dentistprofile",
            name="user_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dentistprofile",
            name="website",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="dentistprofile",
            name="years_of_experience",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="education",
            name="degree",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="education",
            name="dentist_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="portofolio.dentistprofile",
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="institution",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="education",
            name="year",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="faq",
            name="answer",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="faq",
            name="dentist_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="portofolio.dentistprofile",
            ),
        ),
        migrations.AddField(
            model_name="faq",
            name="question",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="dentist_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="portofolio.dentistprofile",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="image",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="dentist_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="portofolio.dentistprofile",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="duration_minutes",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="name",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="skill",
            name="category",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="skill",
            name="dentist_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="portofolio.dentistprofile",
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="socialmedia",
            name="dentist_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="portofolio.dentistprofile",
            ),
        ),
        migrations.AddField(
            model_name="socialmedia",
            name="platform",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="socialmedia",
            name="url",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="dentist_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="portofolio.dentistprofile",
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="feedback",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="patient_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="rating",
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(null=True)),
                ("time", models.TimeField(null=True)),
                ("notes", models.TextField(null=True)),
                ("status", models.CharField(max_length=20, null=True)),
                (
                    "dentist_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portofolio.dentistprofile",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.URLField(null=True)),
                ("description", models.TextField(null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "dentist_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portofolio.dentistprofile",
                    ),
                ),
            ],
        ),
    ]
