# Generated by Django 5.2.5 on 2025-10-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portofolio", "0007_testimonial_created_at_testimonial_patient_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dentistprofile",
            name="phone_number",
            field=models.CharField(max_length=11, null=True),
        ),
    ]
