# Generated by Django 5.2.5 on 2025-11-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portofolio", "0008_alter_dentistprofile_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dentistprofile",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
