# Generated by Django 5.2.5 on 2026-02-17 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portofolio", "0009_alter_dentistprofile_profile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="awards",
            name="dentist_id",
        ),
        migrations.RemoveField(
            model_name="certification",
            name="dentist_id",
        ),
        migrations.RemoveField(
            model_name="education",
            name="dentist_id",
        ),
        migrations.RemoveField(
            model_name="experience",
            name="dentist_id",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="dentist_id",
        ),
        migrations.RemoveField(
            model_name="project",
            name="dentist_id",
        ),
        migrations.RemoveField(
            model_name="service",
            name="dentist_id",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="dentist_id",
        ),
        migrations.RemoveField(
            model_name="socialmedia",
            name="dentist_id",
        ),
        migrations.RenameField(
            model_name="dentistprofile",
            old_name="bio",
            new_name="about_me",
        ),
        migrations.RemoveField(
            model_name="dentistprofile",
            name="clinic_address",
        ),
        migrations.RemoveField(
            model_name="dentistprofile",
            name="clinic_name",
        ),
        migrations.RemoveField(
            model_name="dentistprofile",
            name="website",
        ),
        migrations.DeleteModel(
            name="Article",
        ),
        migrations.DeleteModel(
            name="Awards",
        ),
        migrations.DeleteModel(
            name="Certification",
        ),
        migrations.DeleteModel(
            name="Education",
        ),
        migrations.DeleteModel(
            name="Experience",
        ),
        migrations.DeleteModel(
            name="FAQ",
        ),
        migrations.DeleteModel(
            name="Project",
        ),
        migrations.DeleteModel(
            name="Service",
        ),
        migrations.DeleteModel(
            name="Skill",
        ),
        migrations.DeleteModel(
            name="SocialMedia",
        ),
    ]
