# Generated by Django 4.2.11 on 2026-02-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0010_remove_awards_dentist_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='duration',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='way_of_communication',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
