from django.db import models
from apps.users.models import User
from apps.portofolio.models import DentistProfile

# Create your models here.

# Patient Profile
class PatientProfile(models.Model):
    id = models.AutoField(primary_key=True)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=255, null=True)
    phone = models.CharField(max_length=11, null=True)
    gender = models.CharField(max_length=10, null=True)
    address = models.CharField(max_length=30, null=True)
    date_of_birth = models.DateField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.name if self.name else "Patient Profile"


class AITreatmentSuggestion(models.Model):
    """
    Stores treatment suggestions generated by AI for a patient.
    Doctors can review and approve/reject these suggestions.
    """
    patient = models.ForeignKey(User, on_delete=models.CASCADE, related_name="ai_suggestions")
    input_data = models.TextField(help_text="Symptoms or input data provided by patient")
    # AI Outputs
    ai_diagnosis = models.TextField(help_text="Diagnosis predicted by AI")
    ai_treatment_plan = models.TextField(help_text="Treatment plan suggested by AI")
    confidence_score = models.FloatField(
        help_text="AI confidence score (0-100)", null=True, blank=True
    )

    # Doctor Review
    reviewed_by = models.ForeignKey(
        DentistProfile, on_delete=models.SET_NULL, null=True, blank=True
    )
    VERDICT_CHOICES = [
        ("pending", "Pending Review"),
        ("approved", "Approved"),
        ("rejected", "Rejected"),
        ("modified", "Modified & Approved"),
    ]
    doctor_verdict = models.CharField(max_length=20, choices=VERDICT_CHOICES, default="pending")
    doctor_notes = models.TextField(blank=True, null=True, help_text="Doctor's feedback on the AI suggestion")

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"AI Suggestion for {self.patient.username} - {self.doctor_verdict}"


# Medical Record
class MedicalRecord(models.Model):
    patient_id = models.ForeignKey(PatientProfile, on_delete=models.CASCADE, null=True)

    doctor_id = models.ForeignKey(DentistProfile, on_delete=models.CASCADE, null=True)

    ai_suggestion = models.OneToOneField(AITreatmentSuggestion, on_delete=models.SET_NULL, null=True, blank=True, related_name="medical_record")
    date = models.DateField(null=True)
    diagnosis = models.CharField(max_length=255, null=True)
    treatment = models.CharField(max_length=255, null=True)
    notes = models.TextField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.diagnosis if self.diagnosis else "Medical Record"

# Prescription
class Prescription(models.Model):
    medical_record = models.ForeignKey(MedicalRecord, on_delete=models.CASCADE, null=True)
    medicine_name = models.CharField(max_length=255, null=True)
    dosage = models.CharField(max_length=255, null=True)
    duration = models.IntegerField(null=True)
    instructions = models.TextField(null=True)
    prescribed_date = models.DateField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.medicine_name if self.medicine_name else "Prescription"


class MedicalAttachment(models.Model):
    """
    X-Rays, Lab Results, or other files attached to a medical record.
    Stored as a URL link to avoid hosting large files directly on the server if needed.
    """
    record = models.ForeignKey(
        MedicalRecord, on_delete=models.CASCADE, related_name="attachments"
    )
    file_url = models.URLField(
        help_text="Direct link to the file (e.g., S3, Cloudinary, or external host)",
        max_length=500,
    )
    description = models.CharField(max_length=255, blank=True)
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Attachment for {self.record}"


# Patient and Doctor Relationship
class PatientDoctorRelationship(models.Model):
    patient_id = models.ForeignKey(PatientProfile, on_delete=models.CASCADE, null=True, related_name='assigned_doctors')
    doctor_id = models.ForeignKey(DentistProfile, on_delete=models.CASCADE, null=True, related_name='assigned_patients')
    status = models.CharField(max_length=20, null=True, choices=[('active', 'Active'), ('inactive', 'Inactive'),('pending', 'Pending')] , default='active')
    assigned_date = models.DateField(auto_now_add=True,null=True)
    notes = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        patient_name = self.patient_id.name if self.patient_id else "Unknown Patient"
        doctor_name = self.doctor_id.user_id.username if self.doctor_id and self.doctor_id.user_id else "Unknown Doctor"
        return f"{patient_name} - {doctor_name} ({self.status})"
    class Meta:
        unique_together = ('patient_id', 'doctor_id')
