from django.db import models
from apps.users.models import User
from apps.portofolio.models import DentistProfile

# Create your models here.

class PatientProfile(models.Model):
    id = models.AutoField(primary_key=True)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=255, null=True)
    phone = models.CharField(max_length=11, null=True)
    gender = models.CharField(max_length=10, null=True)
    address = models.CharField(max_length=30, null=True)
    date_of_birth = models.DateField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.name if self.name else "Patient Profile"


class AIResult(models.Model):
    """
    Stores results generated by AI for a patient.
    Doctors can review and approve/reject these suggestions.
    """
    patient = models.ForeignKey(User, on_delete=models.CASCADE, related_name="ai_results")
    predicted_class = models.CharField(max_length=255, null=True)
    confidence_score = models.FloatField(null=True)
    probabilities = models.JSONField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f"AI Result for {self.patient.username}"

class MedicalRecord(models.Model):
    patient_id = models.ForeignKey(PatientProfile, on_delete=models.CASCADE, null=True)
    ai_result = models.OneToOneField(AIResult, on_delete=models.SET_NULL, null=True, blank=True, related_name="medical_record")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return f"Medical Record for {self.patient_id.name}"

class MedicalAttachment(models.Model):
    medical_record = models.ForeignKey(MedicalRecord, on_delete=models.CASCADE, null=True, related_name="attachments")
    file_url = models.URLField(max_length=500, null=True)
    description = models.CharField(max_length=255, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f"Attachment for {self.medical_record}"

class PatientDoctorRelationship(models.Model):
    patient_id = models.ForeignKey(PatientProfile, on_delete=models.CASCADE, null=True, related_name='assigned_doctors')
    doctor_id = models.ForeignKey(DentistProfile, on_delete=models.CASCADE, null=True, related_name='assigned_patients')
    status = models.CharField(max_length=20, null=True, choices=[('active', 'Active'), ('inactive', 'Inactive'),('pending', 'Pending')] , default='active')
    assigned_date = models.DateField(auto_now_add=True,null=True)
    notes = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        patient_name = self.patient_id.name if self.patient_id else "Unknown Patient"
        doctor_name = self.doctor_id.user_id.username if self.doctor_id and self.doctor_id.user_id else "Unknown Doctor"
        return f"{patient_name} - {doctor_name} ({self.status})"
    class Meta:
        unique_together = ('patient_id', 'doctor_id')
