# Generated by Django 5.2.5 on 2025-09-01 04:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicappointment',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.clinicprofile'),
        ),
        migrations.AddField(
            model_name='clinicappointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicappointment',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='clinicappointment',
            name='doctor_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.clinicdoctors'),
        ),
        migrations.AddField(
            model_name='clinicappointment',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='clinicappointment',
            name='patient_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clinicappointment',
            name='patient_phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clinicappointment',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='cliniccontactmessage',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.clinicprofile'),
        ),
        migrations.AddField(
            model_name='cliniccontactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cliniccontactmessage',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='cliniccontactmessage',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cliniccontactmessage',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='clinicdoctors',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.clinicprofile'),
        ),
        migrations.AddField(
            model_name='clinicdoctors',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicdoctors',
            name='doc_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clinicgallary',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.clinicprofile'),
        ),
        migrations.AddField(
            model_name='clinicgallary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicgallary',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='clinicgallary',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='clinicgallary',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clinicprofile',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='clinicprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinicprofile',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='clinicprofile',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='clinicprofile',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clinicprofile',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clinicprofile',
            name='website',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='clinicreview',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.clinicprofile'),
        ),
        migrations.AddField(
            model_name='clinicreview',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='clinicreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicreview',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinicreview',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='clinicservice',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.clinicprofile'),
        ),
        migrations.AddField(
            model_name='clinicservice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicservice',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='clinicservice',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clinicservice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='clinicworkinghours',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.clinicprofile'),
        ),
        migrations.AddField(
            model_name='clinicworkinghours',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicworkinghours',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='clinicworkinghours',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clinicworkinghours',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
