# Generated by Django 5.2.4 on 2025-11-01 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_clinicappointment_clinic_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClinicGallary',
            new_name='ClinicGallery',
        ),
    ]
