# Generated by Django 4.2.11 on 2025-12-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinic", "0004_clinicappointment_patient_clinicappointment_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliniccontactmessage",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="cliniccontactmessage",
            name="start_time",
        ),
        migrations.AddField(
            model_name="cliniccontactmessage",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="cliniccontactmessage",
            name="message",
            field=models.TextField(null=True),
        ),
    ]
